@echo off
title RestaurantOS Server
cd /d "%~dp0server"
echo [Server] Installing dependencies...
call npm install --silent
echo [Server] Generating Prisma client...
call npx prisma generate --no-hints 2>nul
echo [Server] Pushing database schema...
call npx prisma db push --accept-data-loss 2>nul
echo [Server] Seeding demo data...
call npx tsx prisma/seed.ts
echo.
echo [Server] Starting on http://localhost:3001 ...
echo.
npx tsx src/index.ts
pause
